version: '3'
services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=odoo
      - DATABASE_PASSWORD=odoo
      - DATABASE_NAME=odoo
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

volumes:
  odoo_db_data: